// AUTO-GENERATED barrel. Source of truth: ../../components/*

// Base UI primitives
export * from '@/components/ui/accordion'
export * from '@/components/ui/alert'
export * from '@/components/ui/avatar'
export * from '@/components/ui/badge'
export * from '@/components/ui/button'
export * from '@/components/ui/card'
export * from '@/components/ui/checkbox'
export * from '@/components/ui/dialog'
export * from '@/components/ui/dropdown-menu'
export * from '@/components/ui/input'
export * from '@/components/ui/label'
export * from '@/components/ui/popover'
export * from '@/components/ui/progress'
export * from '@/components/ui/radio-group'
export * from '@/components/ui/scroll-area'
export * from '@/components/ui/select'
export * from '@/components/ui/separator'
export * from '@/components/ui/skeleton'
export * from '@/components/ui/slider'
export * from '@/components/ui/switch'
export * from '@/components/ui/table'
export * from '@/components/ui/tabs'
export * from '@/components/ui/textarea'
export * from '@/components/ui/toggle'
export * from '@/components/ui/tooltip'

// Trading widgets
export * from '@/components/trading/group-color-selector'
export * from '@/components/trading/widget'
export * from '@/components/trading/deals-list'
export * from '@/components/trading/instrument-search'
export * from '@/components/trading/order-book'
export * from '@/components/trading/order-form'
export * from '@/components/trading/portfolio'
export * from '@/components/trading/searchable-select'
export * from '@/components/trading/timeframe-select'
